[ADD] 이벤트 NFC 기능 & Lo-fi UI 추가
letswiftconf/LetSwift pull request #189
Opened 2024-09-17 09:52 UTC by JUNY0110

### 작업 내역
- 이벤트 NFC 기능 연결
- 이벤트탭 Lo-fi UI 추가 (UI 디자인 - 23일 예정)
  - (임시) 스탬프 적립 성공 시: Cell 색상 변경(회색 -> 빨강)
  - (임시) 스탬프 적립 실패 시: 변화 없음.

|적립 성공|적립 실패(Empty NFC Tag)|
|:-:|:-:|
| ![image](https://github.com/user-attachments/assets/31172340-8d3d-44c8-a7e4-5525ef176183) | ![image](https://github.com/user-attachments/assets/1e0c26f5-459b-4e98-bad0-e0d8eace6cf7) |

2024-09-18 16:24 UTC, doitduri requested changes
Identifiers > Capabilities > NFC 추가는 따로 요청하도록 하겠습니다!
그리고 계정 추가가 안되어서 개인 계정으로 한 것으로 확인되는데 혹시 맞으실까요? (맞다면, 빠른 시일 내에 추가해서 확인 할 수 있도록 조치 취하겠습니다)

2024-09-18 16:24 UTC, doitduri commented on LetSwift/View/Events/Views/EventsView.swift
> +            .foregroundStyle(Color(.systemGroupedBackground))
figma 상 color 값 적용이 없어서, 한번 확인 부탁드리겠습니다 :)

2024-09-18 16:24 UTC, doitduri commented on LetSwift/View/Events/Views/EventsView.swift
> +            Text("스탬프를 모아보세요")
localizable 파일로 관리하는건 어떨까요? (현재 대부분 localizable 값을 사용하고 있어서요~)

2024-09-18 16:24 UTC, doitduri commented on LetSwift/View/Events/ViewModels/EventViewModel.swift
> +import Foundation
미사용 파일은 관리 차원에서 삭제 부탁드립니다!

2024-09-23 05:12 UTC, JUNY0110 commented on LetSwift/View/Events/Views/EventsView.swift
> +            .foregroundStyle(Color(.systemGroupedBackground))
> figma 상 color 값 적용이 없어서, 한번 확인 부탁드리겠습니다 :)

6bd2461
content()의 RoundedRectangle은 초기에 제공해주신 코드를 유지했었던 흔적인데, 현재는 필요 없으므로 삭제했습니다:)

2024-09-23 05:31 UTC, JUNY0110 commented on LetSwift/View/Events/Views/EventsView.swift
> +            Text("스탬프를 모아보세요")
> localizable 파일로 관리하는건 어떨까요? (현재 대부분 localizable 값을 사용하고 있어서요~)

0e450bb
Localizable 스타일에 맞게 수정했습니다.

|**수정 전**|![스크린샷 2024-09-23 오후 2 30 11](https://github.com/user-attachments/assets/4b2da1ee-7a02-408c-9f49-ffd46a6e2b8d)|
|:-:|:-:|
|**수정 후**|![스크린샷 2024-09-23 오후 2 24 02](https://github.com/user-attachments/assets/a5bfb9fb-793b-4430-8e52-e55b28c8eae1)|

2024-09-23 05:33 UTC, JUNY0110 commented
> Identifiers > Capabilities > NFC 추가는 따로 요청하도록 하겠습니다! (제가 권한이 없어서 이 부분 확인해볼께요) 그리고 계정 추가가 안되어서 개인 계정으로 한 것으로 확인되는데 혹시 맞으실까요? (맞다면, 빠른 시일 내에 추가해서 확인 할 수 있도록 조치 취하겠습니다)
> 
> 수고 많으셨습니다 ㅎㅎ

맞습니다! NFC는 개인 계정으로 테스트 및 확인했습니다.
PR 확인이 늦어져서 죄송합니다 ㅠ

2024-09-23 05:33 UTC, JUNY0110 commented on LetSwift/View/Events/ViewModels/EventViewModel.swift
> +import Foundation
> 미사용 파일은 관리 차원에서 삭제 부탁드립니다!

6ecf28d
삭제했습니다!

2024-09-23 05:34 UTC, doitduri approved these changes
빠른 반영 감사합니다 :)

2024-09-23 05:34 UTC, merged

2024-09-23 05:34 UTC, JUNY0110 commented on LetSwift/View/Events/ViewModels/EventViewModel.swift
> +import Foundation
> 미사용 파일은 관리 차원에서 삭제 부탁드립니다!

6ecf28d
삭제했습니다!